"use strict";

export default {
  FRAMERATE = 60,
  TILE_SIZE = 32,
  SLOT_SIZE = TILE_SIZE + 6,

  MAP_LAYERS = 6,
  MAP_COLUMNS = 12,
  MAP_ROWS = 12,

  MAX_MAPS = 10,
  MAX_USERS = 100,
  MAX_SPRITES = 13,
  MAX_EFFECTS = 70,

  INVENTORY_SIZE = 20,
  EQUIPMENT_SIZE = 5,

  START_MAP = 1,
  START_X = 5,
  START_Y = 5
};