'use strict';

module.exports = {
	FRAMERATE: 60,
	TILE_SIZE: 32,
	SLOT_SIZE: TILE_SIZE + 6,

	MAX_MAPS: 10,
	MAX_USERS: 100,

	
	MAP_LAYERS: 6,
	MAP_COLUMNS: 12,
	MAP_ROWS: 12,
	MAP_LEFT: 0,																									// x = 0 to 384
	MAP_TOP: 0,																									// y = 0 to 384

	MAP_WIDTH: MAP_COLUMNS * TILE_SIZE,															// width = 384
	MAP_HEIGHT: MAP_ROWS * TILE_SIZE,																// height = 384
	MAP_RIGHT: MAP_LEFT + MAP_WIDTH,
	MAP_BOTTOM: MAP_TOP + MAP_HEIGHT,


	INVENTORY_COLUMNS: 5,
	INVENTORY_ROWS: 4,
	INVENTORY_LEFT: MAP_RIGHT + 32,																	// x = 416
	INVENTORY_TOP: MAP_BOTTOM / 4,																	// y = 96

	INVENTORY_SIZE: INVENTORY_COLUMNS * INVENTORY_ROWS,							// size = 20
	INVENTORY_WIDTH: INVENTORY_COLUMNS * SLOT_SIZE,									// wdith = 190
	INVENTORY_HEIGHT: INVENTORY_ROWS * SLOT_SIZE,										// height = 152
	INVENTORY_RIGHT: INVENTORY_LEFT + INVENTORY_WIDTH,								// x = 606
	INVENTORY_BOTTOM: INVENTORY_TOP + INVENTORY_HEIGHT,							// y = 248


	EQUIPMENT_LEFT: INVENTORY_LEFT,																	// x = 416
	EQUIPMENT_TOP: INVENTORY_BOTTOM + 2,														// y = 250
	EQUIPMENT_COLUMNS: 5,
	EQUIPMENT_ROWS: 1,

	EQUIPMENT_SIZE: EQUIPMENT_COLUMNS * EQUIPMENT_ROWS,							// size = 5
	EQUIPMENT_WIDTH: EQUIPMENT_COLUMNS * SLOT_SIZE,									// width = 190
	EQUIPMENT_HEIGHT: EQUIPMENT_ROWS * SLOT_SIZE,										// height = 38
	EQUIPMENT_RIGHT: EQUIPMENT_LEFT + EQUIPMENT_WIDTH,								// x = 606
	EQUIPMENT_BOTTOM: EQUIPMENT_TOP + EQUIPMENT_WIDTH,							// y = 288


	SPRITESHEET_COLUMNS: 13,
	SPRITESHEET_ROWS: 13,
	EFFECTSHEET_COLUMNS: 9,
	EFFECTSHEET_ROWS: 70,
	
	START_MAP: 1,
	START_X: 5,
	START_Y: 5
};